import { Collection, Product, UserProfile, Order, Commission, Payout, JournalPost, CMSBlock } from './types';

export const INITIAL_COLLECTIONS: Collection[] = [
  {
    id: 'col-platinum',
    slug: 'platinum-collection',
    title: 'Platinum Collection',
    tier: 'platinum',
    description: 'Bespoke heirloom coats crafted with pure gold/silver metallic zari, real silk resham, and up to 140 hours of hand needlework.',
    hero_image_url: '/uploads/2026/06/Mens-Premium-Prince-Coat-4.webp',
    price_range_label: '£1,400 – £2,800',
    sort_order: 1,
  },
  {
    id: 'col-gold',
    slug: 'gold-collection',
    title: 'Gold Heritage Collection',
    tier: 'gold',
    description: 'Classic artisanal silhouettes featuring botanical zardozi embroidery on heavyweight velvets and imported brocades.',
    hero_image_url: '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco.webp',
    price_range_label: '£900 – £1,400',
    sort_order: 2,
  },
  {
    id: 'col-silver',
    slug: 'silver-collection',
    title: 'Silver Classic Collection',
    tier: 'silver',
    description: 'Refined formal coats and tailored jackets with subtle marori borders and structured wool drape.',
    hero_image_url: '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket.webp',
    price_range_label: '£650 – £900',
    sort_order: 3,
  },
  {
    id: 'col-essentials',
    slug: 'essentials-collection',
    title: 'Atelier Essentials',
    tier: 'essentials',
    description: 'Elevated everyday layering pieces, raw silk waistcoats, and minimalist embroidered statement garments.',
    hero_image_url: '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer.webp',
    price_range_label: '£350 – £650',
    sort_order: 4,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    slug: 'mens-premium-velvet-prince-coat',
    title: "Men's Imperial Gold Velvet Prince Coat",
    collection_id: 'col-platinum',
    base_price_gbp: 1450,
    regular_price_gbp: 1650,
    sale_price_gbp: 1450,
    description: 'An exceptional masterpiece of South Asian haute couture. Hand-embroidered with pure 24k-gold-plated metallic zari thread across a rich midnight-emerald velvet canvas. Features signature mandarin collar, handmade knot buttons, and structured canvassed chest.',
    featured_image_url: '/uploads/2026/06/Mens-Premium-Prince-Coat-4.webp',
    gallery_images: [
      '/uploads/2026/06/Mens-Premium-Prince-Coat-4.webp',
      '/uploads/2026/06/Mens-Premium-Prince-Coat-2.webp',
      '/uploads/2026/06/Mens-Premium-Prince-Coat-3.webp',
      '/uploads/2026/06/Mens-Premium-Prince-Coat.webp',
    ],
    stock_status: 'in_stock',
    stock_quantity: 4,
    is_featured: true,
    lead_time_weeks: 4,
    collection: INITIAL_COLLECTIONS[0],
    acf_meta: {
      fabric_composition: '100% Italian Silk Micro-Velvet (520 GSM) & Pure Mulberry Silk Lining',
      embroidery_technique: 'Hand Zardozi with Metallic Gold Bullion, French Knots & Sequins',
      embroidery_hours: 120,
      embroidery_placement: ['Mandarin Collar', 'Cuffs', 'Lapels', 'Pocket Flaps', 'Back Vent'],
      care_instructions: 'Specialist Dry Clean Only. Store in breathable garment bag away from direct sunlight.',
      product_colors: [
        { name: 'Imperial Emerald', hex: '#162923' },
        { name: 'Royal Midnight Navy', hex: '#0D1B2A' },
        { name: 'Sovereign Black', hex: '#0A0A0A' },
      ],
      product_highlights: [
        { highlight: '120+ hours of painstaking hand needlework by master ustads' },
        { highlight: 'Full floating horsehair canvas for an immaculate drape' },
        { highlight: 'Real gold metallic dabka and metallic bullion embroidery' },
        { highlight: 'Complimentary DHL Express worldwide insured shipping' },
      ],
    },
    created_at: '2026-06-01T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
  {
    id: 'prod-002',
    slug: 'burgundy-art-deco-silver-embroidered-blazer',
    title: 'Burgundy Art Deco Silver Embroidered Blazer',
    collection_id: 'col-gold',
    base_price_gbp: 1150,
    regular_price_gbp: 1350,
    sale_price_gbp: 1150,
    description: 'A striking fusion of European Art Deco geometry and Mughal heritage needlework. Heavyweight burgundy velvet adorned with real silver tilla and metallic bullion.',
    featured_image_url: '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco.webp',
    gallery_images: [
      '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco.webp',
      '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco-2.webp',
      '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco-3.webp',
      '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco-4.webp',
    ],
    stock_status: 'in_stock',
    stock_quantity: 6,
    is_featured: true,
    lead_time_weeks: 3,
    collection: INITIAL_COLLECTIONS[1],
    acf_meta: {
      fabric_composition: 'Imported Crimson Velvet (480 GSM) with Bemberg Cupro Lining',
      embroidery_technique: 'Silver Tilla Thread & Metallic Nakshi Work',
      embroidery_hours: 85,
      care_instructions: 'Specialist Dry Clean Only.',
      product_colors: [
        { name: 'Deep Burgundy', hex: '#4A0E17' },
        { name: 'Midnight Onyx', hex: '#0B0B0C' },
      ],
      product_highlights: [
        { highlight: 'Precision Art Deco geometric silver embroidery' },
        { highlight: 'Hand-shaped peak lapels and structured shoulders' },
      ],
    },
    created_at: '2026-06-05T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
  {
    id: 'prod-003',
    slug: 'black-brocade-tuxedo-jacket',
    title: 'Black Silk Brocade Royal Tuxedo Jacket',
    collection_id: 'col-silver',
    base_price_gbp: 850,
    regular_price_gbp: 990,
    sale_price_gbp: 850,
    description: 'Impeccable evening formalwear crafted in woven floral silk brocade with lustrous satin shawl lapels and hand-covered satin buttons.',
    featured_image_url: '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket.webp',
    gallery_images: [
      '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket.webp',
      '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket-2.webp',
      '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket-3.webp',
      '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket-4.webp',
    ],
    stock_status: 'in_stock',
    stock_quantity: 8,
    is_featured: true,
    lead_time_weeks: 3,
    collection: INITIAL_COLLECTIONS[2],
    acf_meta: {
      fabric_composition: 'Jacquard Woven Silk Brocade with Pure Silk Satin Facings',
      embroidery_technique: 'Intricate Floral Weave with Subtle Thread Accents',
      embroidery_hours: 45,
      care_instructions: 'Dry Clean Only.',
      product_colors: [
        { name: 'Onyx Brocade', hex: '#111111' },
        { name: 'Midnight Navy', hex: '#14213D' },
      ],
      product_highlights: [
        { highlight: 'Lustrous satin shawl lapel with matching jetted pockets' },
        { highlight: 'Single-button closure with hand-covered silk button' },
      ],
    },
    created_at: '2026-06-10T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
  {
    id: 'prod-004',
    slug: 'black-wool-blend-tailored-blazer',
    title: 'Black Wool-Blend Tailored Statement Blazer',
    collection_id: 'col-essentials',
    base_price_gbp: 550,
    regular_price_gbp: 650,
    sale_price_gbp: 550,
    description: 'A versatile essential for black-tie galas and luxury evening events. Tailored from super 140s wool with subtle metallic border detailing on the collar.',
    featured_image_url: '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer.webp',
    gallery_images: [
      '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer.webp',
      '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer-2.webp',
      '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer-3.webp',
      '/uploads/2026/06/Black-Wool-Blend-Tailored-Blazer-4.webp',
    ],
    stock_status: 'in_stock',
    stock_quantity: 12,
    is_featured: false,
    lead_time_weeks: 2,
    collection: INITIAL_COLLECTIONS[3],
    acf_meta: {
      fabric_composition: 'Super 140s Merino Wool (80%) & Cashmere Blend (20%)',
      embroidery_technique: 'Fine Marori Stitching on Collar & Cuff Borders',
      embroidery_hours: 30,
      care_instructions: 'Professional Dry Clean Only.',
      product_colors: [
        { name: 'Jet Black', hex: '#050505' },
        { name: 'Charcoal Slate', hex: '#2B2D42' },
      ],
      product_highlights: [
        { highlight: 'Hand-tailored lightweight half-canvas construction' },
        { highlight: 'Breathable cupro silk lining with interior passport pocket' },
      ],
    },
    created_at: '2026-06-15T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
  {
    id: 'prod-005',
    slug: 'burgundy-velvet-tuxedo-jacket',
    title: 'Burgundy Imperial Velvet Tuxedo Jacket',
    collection_id: 'col-gold',
    base_price_gbp: 1250,
    regular_price_gbp: 1450,
    sale_price_gbp: 1250,
    description: 'Opulent deep wine velvet tailored into a sharp double-breasted evening silhouette with delicate metallic cord embroidery along the peak lapels.',
    featured_image_url: '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket.webp',
    gallery_images: [
      '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket.webp',
      '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket-2.webp',
      '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket-3.webp',
      '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket-4.webp',
    ],
    stock_status: 'in_stock',
    stock_quantity: 5,
    is_featured: true,
    lead_time_weeks: 4,
    collection: INITIAL_COLLECTIONS[1],
    acf_meta: {
      fabric_composition: 'Pure Silk Velvet (500 GSM)',
      embroidery_technique: 'Hand Zardozi & Metallic Thread Piping',
      embroidery_hours: 90,
      care_instructions: 'Dry Clean Only.',
      product_colors: [
        { name: 'Royal Burgundy', hex: '#540B0E' },
        { name: 'Imperial Emerald', hex: '#162923' },
      ],
      product_highlights: [
        { highlight: 'Double-breasted 6x2 button stance with satin facing' },
        { highlight: 'Silk velvet pile with unmatched depth and shimmer' },
      ],
    },
    created_at: '2026-06-18T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
  {
    id: 'prod-006',
    slug: 'daroodi-bespoke-ceremonial-regalia',
    title: 'Bespoke Ceremonial Robes & Fraternal Regalia',
    collection_id: 'col-platinum',
    base_price_gbp: 1800,
    regular_price_gbp: 2100,
    sale_price_gbp: 1800,
    description: 'Custom regalia, heraldic ceremonial robes, and fraternal embroidery designed for orders, chancellors, and dignitaries worldwide.',
    featured_image_url: '/uploads/2026/05/daroodi-ceremonial-robes.jpg',
    gallery_images: [
      '/uploads/2026/05/daroodi-ceremonial-robes.jpg',
      '/uploads/2026/05/daroodi-masonic-regalia.jpg',
      '/uploads/2026/05/daroodi-bishops-robes.jpg',
      '/uploads/2026/05/daroodi-fraternal-uniforms.jpg',
    ],
    stock_status: 'made_to_order',
    stock_quantity: 2,
    is_featured: true,
    lead_time_weeks: 6,
    collection: INITIAL_COLLECTIONS[0],
    acf_meta: {
      fabric_composition: 'Heavyweight Damask Silk & Gold Lame Cloth',
      embroidery_technique: 'Heraldic Gold Bullion Crests & Raised Padded Zardozi',
      embroidery_hours: 150,
      care_instructions: 'Museum Quality Archival Preservation Care.',
      product_colors: [
        { name: 'Ecclesiastical Crimson', hex: '#7209B7' },
        { name: 'Heraldic Gold', hex: '#C9A84C' },
      ],
      product_highlights: [
        { highlight: 'Custom heraldic insignias and guild crests digitized and hand-stitched' },
        { highlight: 'Worn by dignitaries, order chancellors, and ecclesiastical leaders' },
      ],
    },
    created_at: '2026-06-20T00:00:00Z',
    updated_at: '2026-08-22T00:00:00Z',
  },
];

export const INITIAL_JOURNAL_POSTS: JournalPost[] = [
  {
    id: 'post-001',
    slug: 'what-is-zardozi-hand-embroidery-the-definitive-guide',
    title: 'What Is Zardozi Hand Embroidery? The Definitive Guide',
    excerpt: 'Explore the 500-year history of Zardozi needlework, genuine 24k bullion coils, and why this slow art form remains the pinnacle of luxury menswear.',
    content: `### The Imperial Heritage of Zardozi Needlework
Zardozi—derived from the Persian words *zar* (gold) and *dozi* (embroidery)—is an ancient court embroidery technique originally reserved for royal coronation robes, velvet tents of emperors, and scabbards of maharajas.

### The Tools of the Master Ustad
1. **The Karchob Loom**: A heavy horizontal wooden frame that holds rich Italian silk velvet taut under extreme tension.
2. **Ari (Needle Hook)**: A sharp pencil-fine awl hooked at the tip, enabling artisans to manipulate metal coils with sub-millimeter dexterity.
3. **Dabka & Bullion Coils**: Microscopic coiled springs of gold and silver-plated wire cut into millimeter fragments and hand-threaded onto fabric.

### Why Machine Embroidery Cannot Replicate Zardozi
Modern industrial machines can produce flat satin stitches, but they cannot sculpt three-dimensional bullion relief or adjust thread tension across velvet nap without crushing the pile. Each Daroodi garment takes up to 140 hours of focused manual needlework.`,
    cover_image_url: '/uploads/2026/06/Mens-Premium-Prince-Coat-4.webp',
    published_at: '2026-08-15',
    read_time_minutes: 6,
    author: 'Master Ustad Tariq Mansoor',
  },
  {
    id: 'post-002',
    slug: 'history-of-the-prince-coat',
    title: 'The History of the Prince Coat: From Mughal Durbars to Global Galas',
    excerpt: 'How the aristocratic Nehru/Jodhpur jacket evolved into the modern embroidered Prince Coat worn at international black-tie galas.',
    content: `### The Royal Evolution of the High-Collar Silhouette
The Prince Coat combines the structured mandarin collar of the historic *Achkan* with the clean-cut chest canvas and shoulder drape of British bespoke tailoring.

### Styling for Modern Evening Wear:
- **Trousers**: Match with structured barathea wool or silk-blend trousers with a crisp quarter-break.
- **Footwear**: Custom velvet Albert slippers with monogram crests or wholecut black Oxford leather shoes.
- **Lapel Accent**: Pair with bespoke enamel cufflinks and hand-turned metal buttons.`,
    cover_image_url: '/uploads/2026/06/Burgundy-Blazer-·-Silver-Art-Deco.webp',
    published_at: '2026-08-12',
    read_time_minutes: 5,
    author: 'Sarmad Daroodi, Creative Director',
  },
  {
    id: 'post-003',
    slug: 'dabka-coil-work-explained',
    title: 'Dabka Coil Work Explained: The Anatomy of Metallic Bullion',
    excerpt: 'A masterclass into how micro-coiled brass and silver wires create the shimmering dimensional relief on Daroodi lapels.',
    content: `### The Physics of Hand-Coiled Metallic Wire
Dabka is crafted by tightly coiling razor-thin wire around needle mandates to form miniature hollow springs. The artisan cuts each spring into precise 2mm segments before anchoring them to the fabric with hidden silk stitches.

When light hits these faceted coils, it reflects across hundreds of microscopic angles, producing the luminous glow distinctive to Daroodi Platinum pieces.`,
    cover_image_url: '/uploads/2026/06/Black-Brocade-Tuxedo-Jacket.webp',
    published_at: '2026-08-08',
    read_time_minutes: 4,
    author: 'Hamza Khan, Senior Pattern Cutter',
  },
  {
    id: 'post-004',
    slug: 'caring-for-velvet-garments',
    title: 'Caring for Velvet Garments: Archival Storage & Maintenance',
    excerpt: 'Essential tips for protecting heavy silk velvet and gold bullion embroidery from humidity, creases, and wear.',
    content: `### Preserving Heirloom Textile Integrity
- **Hanging**: Always use wide-shoulder contoured wooden hangers to preserve shoulder pad architecture.
- **Breathing**: Store only in natural breathable cotton garment bags; avoid sealed plastic covers that trap ambient moisture.
- **Creases**: Never iron velvet directly. Use a handheld vertical steamer from the inside lining, or hang in a humid room.
- **Cleaning**: Specialist dry clean only with certified couture textile preservationists.`,
    cover_image_url: '/uploads/2026/06/Burgundy-Velvet-Tuxedo-Jacket.webp',
    published_at: '2026-08-01',
    read_time_minutes: 4,
    author: 'Daroodi Atelier Conservation Desk',
  },
  {
    id: 'post-005',
    slug: 'black-tie-dress-code-uk-vs-usa',
    title: 'Black Tie Dress Code: UK vs. USA Sartorial Distinctions',
    excerpt: 'Navigating evening formalwear protocols between British royalty galas and American red carpet galas.',
    content: `### Understanding Regional Formalwear Nuances
In British traditional etiquette, formal evening invitations specify strict Black Tie or White Tie protocols. However, modern international galas in London, Dubai, and New York increasingly celebrate elevated statement coats that honor heritage craftsmanship while respecting dress codes.`,
    cover_image_url: '/uploads/2026/05/daroodi-ceremonial-robes.jpg',
    published_at: '2026-07-25',
    read_time_minutes: 5,
    author: 'Sarmad Daroodi, Creative Director',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@daroodi.com',
    full_name: 'Sarmad Daroodi (Chief Maison Master)',
    role: 'super_admin',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'usr-prod-mgr',
    email: 'production@daroodi.com',
    full_name: 'Master Ustad Tariq Mansoor',
    role: 'product_manager',
    created_at: '2026-01-05T00:00:00Z',
  },
  {
    id: 'usr-cm-uk',
    email: 'uk.sales@daroodi.com',
    full_name: 'Sir Arthur Sterling (UK Regional Partner)',
    role: 'country_sales_manager',
    assigned_country: 'GB',
    commission_rate: 0.12,
    created_at: '2026-01-10T00:00:00Z',
  },
  {
    id: 'usr-cm-ae',
    email: 'dubai.sales@daroodi.com',
    full_name: 'Rashid Al-Fardan (UAE Regional Partner)',
    role: 'country_sales_manager',
    assigned_country: 'AE',
    commission_rate: 0.10,
    created_at: '2026-01-12T00:00:00Z',
  },
  {
    id: 'usr-cm-us',
    email: 'us.sales@daroodi.com',
    full_name: 'Kamran Siddiqui (US & Canada Partner)',
    role: 'country_sales_manager',
    assigned_country: 'US',
    commission_rate: 0.10,
    created_at: '2026-01-15T00:00:00Z',
  },
];

export const INITIAL_COMMISSIONS: Commission[] = [
  {
    id: 'comm-101',
    order_id: 'ord-10482',
    recipient_id: 'usr-cm-uk',
    recipient: INITIAL_USERS[2],
    tier_level: 'country_manager_override',
    order_amount: 1450,
    rate: 0.12,
    commission_amount: 174.00,
    status: 'approved',
    approved_by: 'usr-admin-01',
    created_at: '2026-08-18T15:00:00Z',
  },
  {
    id: 'comm-102',
    order_id: 'ord-10483',
    recipient_id: 'usr-cm-ae',
    recipient: INITIAL_USERS[3],
    tier_level: 'country_manager_override',
    order_amount: 1150,
    rate: 0.10,
    commission_amount: 115.00,
    status: 'approved',
    approved_by: 'usr-admin-01',
    created_at: '2026-08-16T10:00:00Z',
  },
  {
    id: 'comm-103',
    order_id: 'ord-10485',
    recipient_id: 'usr-cm-us',
    recipient: INITIAL_USERS[4],
    tier_level: 'country_manager_override',
    order_amount: 1450,
    rate: 0.10,
    commission_amount: 145.00,
    status: 'pending_approval',
    created_at: '2026-08-05T17:00:00Z',
  },
];

export const INITIAL_PAYOUTS: Payout[] = [
  {
    id: 'pay-001',
    recipient_id: 'usr-cm-uk',
    recipient: INITIAL_USERS[2],
    amount: 174.00,
    currency: 'GBP',
    payout_method: 'Barclays International Wire',
    transaction_reference: 'TXN-GB-8930419',
    status: 'completed',
    disbursed_by: 'usr-admin-01',
    disbursed_at: '2026-08-19T10:00:00Z',
    created_at: '2026-08-18T16:00:00Z',
  },
  {
    id: 'pay-002',
    recipient_id: 'usr-cm-ae',
    recipient: INITIAL_USERS[3],
    amount: 115.00,
    currency: 'GBP',
    payout_method: 'Emirates NBD Wire',
    transaction_reference: 'TXN-AE-4091840',
    status: 'completed',
    disbursed_by: 'usr-admin-01',
    disbursed_at: '2026-08-17T11:30:00Z',
    created_at: '2026-08-16T11:00:00Z',
  },
];

export const INITIAL_CMS_BLOCKS: CMSBlock[] = [
  {
    id: 'cms-hero',
    block_key: 'home_hero_banner',
    content_json: {
      headline: 'Imperial Handcrafted Haute Couture',
      tagline: 'Preserving 3 generations of Mughal royal needlework on pure Italian velvets.',
    },
    updated_at: '2026-08-22T00:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-10482',
    order_number: 'DAR-10482',
    customer_id: 'cust-01',
    client_name: 'Lord Alistair Sterling',
    client_email: 'a.sterling@kensington-holdings.co.uk',
    client_country: 'GB',
    product_title: "Men's Imperial Gold Velvet Prince Coat",
    size: '42L (Custom Bespoke)',
    color: 'Imperial Emerald',
    status: 'in_production',
    order_type: 'bespoke_custom',
    currency: 'GBP',
    subtotal: 1450,
    discount_total: 0,
    tax_total: 0,
    shipping_total: 0,
    grand_total: 1450,
    total_amount_gbp: 1450,
    paid: true,
    payment_status: 'paid',
    payment_method: 'Stripe Luxury Vault (Visa Infinite)',
    shipping_address: {
      full_name: 'Lord Alistair Sterling',
      address_line1: '14 Kensington Palace Gardens',
      city: 'London',
      country: 'United Kingdom',
      postal_code: 'W8 4QP',
      phone: '+44 20 7946 0912',
      email: 'a.sterling@kensington-holdings.co.uk',
    },
    created_at: '2026-08-18T14:32:00Z',
    lead_time_weeks: 4,
  },
  {
    id: 'ord-10483',
    order_number: 'DAR-10483',
    customer_id: 'cust-02',
    client_name: 'Sheikh Hamdan Al-Maktoum',
    client_email: 'h.almaktoum@dubairoyal.ae',
    client_country: 'AE',
    product_title: 'Burgundy Art Deco Silver Embroidered Blazer',
    size: '44R (Bespoke)',
    color: 'Deep Burgundy',
    status: 'quality_check',
    order_type: 'bespoke_custom',
    currency: 'GBP',
    subtotal: 1150,
    discount_total: 0,
    tax_total: 0,
    shipping_total: 0,
    grand_total: 1150,
    total_amount_gbp: 1150,
    paid: true,
    payment_status: 'paid',
    payment_method: 'Emirates NBD Wire',
    shipping_address: {
      full_name: 'Sheikh Hamdan Al-Maktoum',
      address_line1: 'Al-Wasl Road, Jumeirah 1',
      city: 'Dubai',
      country: 'United Arab Emirates',
      postal_code: '00000',
      phone: '+971 4 301 8888',
      email: 'h.almaktoum@dubairoyal.ae',
    },
    created_at: '2026-08-16T09:15:00Z',
    lead_time_weeks: 3,
  },
  {
    id: 'ord-10484',
    order_number: 'DAR-10484',
    customer_id: 'cust-03',
    client_name: 'Dr. Tariq Mahmood',
    client_email: 'tariq.mahmood@harleystreet.com',
    client_country: 'GB',
    product_title: 'Black Silk Brocade Royal Tuxedo Jacket',
    size: '40R',
    color: 'Onyx Brocade',
    status: 'dispatched',
    order_type: 'ready_to_wear',
    currency: 'GBP',
    subtotal: 850,
    discount_total: 0,
    tax_total: 0,
    shipping_total: 0,
    grand_total: 850,
    total_amount_gbp: 850,
    paid: true,
    payment_status: 'paid',
    payment_method: 'Mastercard World Elite',
    shipping_address: {
      full_name: 'Dr. Tariq Mahmood',
      address_line1: '98 Harley Street',
      city: 'London',
      country: 'United Kingdom',
      postal_code: 'W1G 7HZ',
      phone: '+44 20 7580 4422',
      email: 'tariq.mahmood@harleystreet.com',
    },
    created_at: '2026-08-12T11:45:00Z',
    lead_time_weeks: 2,
  },
  {
    id: 'ord-10485',
    order_number: 'DAR-10485',
    customer_id: 'cust-04',
    client_name: 'Farhan Zaidi',
    client_email: 'farhan@siliconvalley-capital.com',
    client_country: 'US',
    product_title: "Men's Imperial Gold Velvet Prince Coat",
    size: '38R',
    color: 'Royal Midnight Navy',
    status: 'delivered',
    order_type: 'ready_to_wear',
    currency: 'GBP',
    subtotal: 1450,
    discount_total: 0,
    tax_total: 0,
    shipping_total: 0,
    grand_total: 1450,
    total_amount_gbp: 1450,
    paid: true,
    payment_status: 'paid',
    payment_method: 'American Express Centurion',
    shipping_address: {
      full_name: 'Farhan Zaidi',
      address_line1: '2400 Sand Hill Road, Suite 200',
      city: 'Menlo Park',
      state: 'CA',
      country: 'United States',
      postal_code: '94025',
      phone: '+1 650 854 0000',
      email: 'farhan@siliconvalley-capital.com',
    },
    created_at: '2026-08-05T16:20:00Z',
    lead_time_weeks: 4,
  },
];
